const REQUEST_START = 'SUBMIT_START';
const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
const REQUEST_FAIL = 'SUBMIT_FAIL';
const FETCH_DATA_SUCCESS ='FETCH_DATA_SUCCESS';
const DELETE_DATA_SUCCESS='DELETE_DATA_SUCCESS';

export  {
    REQUEST_START,
    SUBMIT_SUCCESS,
    REQUEST_FAIL,
    FETCH_DATA_SUCCESS,
    DELETE_DATA_SUCCESS
}