const SUBMIT_START = 'SUBMIT_START';
const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
const SUBMIT_FAIL = 'SUBMIT_FAIL';

const FETCH_DATA_START ='FETCH_DATA_START';
const FETCH_DATA_SUCCESS ='FETCH_DATA_SUCCESS';
const FETCH_DATA_FAIL ='FETCH_DATA_FAIL';
export  {
    SUBMIT_START,
    SUBMIT_SUCCESS,
    SUBMIT_FAIL,
    FETCH_DATA_START,
    FETCH_DATA_SUCCESS,
    FETCH_DATA_FAIL
}